#!/bin/bash
#SBATCH --job-name=CISM_ctrl
# KeyCLIM: nn9252k; INES: nn9560k; GREASE: nn8006k
#SBATCH --account=nn8085k
#SBATCH --nodes=4
#SBATCH --ntasks-per-node=128
#SBATCH --time=00:10:00 

## Setting variables and prepare runtime environment:
##----------------------------------------------------
## Recommended safety settings:
set -o errexit # Make bash exit on any error
set -o nounset # Treat unset variables as errors

. arch-modules

# use srun
time srun ./cism_driver cism.config

# Finish the script
exit 0
