#!/bin/bash
#SBATCH --job-name=cism_hist
# KeyCLIM: nn9252k; INES: nn9560k; GREASE: nn8006k
#SBATCH --account=nn8085k
#SBATCH --time=00:10:00
#SBATCH --mem-per-cpu=3G
#SBATCH --ntasks=4

## Setting variables and prepare runtime environment:
##----------------------------------------------------
## Recommended safety settings:
set -o errexit # Make bash exit on any error
set -o nounset # Treat unset variables as errors

. saga-gnu-modules

# use srun on saga
time srun ./cism_driver cism.config

# Finish the script
exit 0
